USE PROYECTO_UTN;

INSERT INTO PERSONA (NOMBRE_PERSONA) VALUES ("MARIANA");
INSERT INTO PERSONA (NOMBRE_PERSONA) VALUES ("PEDRO");

INSERT INTO PRONOSTICO (ID_PERSONA, EQUIPO_UNO, EQUIPO_DOS, GANA_UNO, EMPATE, GANA_DOS) VALUES (1, "ARGENTINA", "ARABIA SAUDITA", "", "", "X");
INSERT INTO PRONOSTICO (ID_PERSONA, EQUIPO_UNO, EQUIPO_DOS, GANA_UNO, EMPATE, GANA_DOS) VALUES (1, "POLONIA", "MEXICO", "", "X", "");
INSERT INTO PRONOSTICO (ID_PERSONA, EQUIPO_UNO, EQUIPO_DOS, GANA_UNO, EMPATE, GANA_DOS) VALUES (1, "ARGENTINA", "MEXICO", "X", "", "");
INSERT INTO PRONOSTICO (ID_PERSONA, EQUIPO_UNO, EQUIPO_DOS, GANA_UNO, EMPATE, GANA_DOS) VALUES (1, "ARABIA SAUDITA", "POLONIA", "", "", "X");
INSERT INTO PRONOSTICO (ID_PERSONA, EQUIPO_UNO, EQUIPO_DOS, GANA_UNO, EMPATE, GANA_DOS) VALUES (2, "ARGENTINA", "ARABIA SAUDITA", "X", "", "");
INSERT INTO PRONOSTICO (ID_PERSONA, EQUIPO_UNO, EQUIPO_DOS, GANA_UNO, EMPATE, GANA_DOS) VALUES (2, "POLONIA", "ARABIA SAUDITA", "", "", "X");
INSERT INTO PRONOSTICO (ID_PERSONA, EQUIPO_UNO, EQUIPO_DOS, GANA_UNO, EMPATE, GANA_DOS) VALUES (2, "ARGENTINA", "MEXICO", "X", "", "");
INSERT INTO PRONOSTICO (ID_PERSONA, EQUIPO_UNO, EQUIPO_DOS, GANA_UNO, EMPATE, GANA_DOS) VALUES (2, "ARABIA SAUDITA", "POLONIA", "X", "", "");
